services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    env_file:
      - ./Backend/env
    environment:
      - PORT=5001
    volumes:
      # keep the container’s node_modules intact:
      - backend_node_modules:/app/node_modules
      # mount your source on top of /app:
      - ./Backend:/app
      # persist uploads
      - ./Backend/uploads:/app/uploads
    ports:
      - "5001:5001"
    command: node server.js

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongo-data:
  backend_node_modules: